spring:
  datasource:
    url: jdbc:postgresql://localhost:12783/leeve_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

spring.liquibase:
  enabled: true
  change-log: db/changelog/db.changelog-master.yaml

spring.servlet.multipart:
  enabled: true
  max-file-size: 10MB
  max-request-size: 10MB

leeve:
  logsFilePath: scans.xlsx