name: Deploy Dev

on:
  push:
    branches:
      - deploy-stage

concurrency:
  group: ${{ github.workflow }}

env:
  AWS_REGION: "us-east-2"
  AWS_ACCOUNT_ID: "339713004094"
  AWS_ROLE_ARN: "arn:aws:iam::339713004094:role/GithubActionsDevIntegrationRole"
  ECS_SERVICE: levee-java-be
  ECS_CLUSTER: levee-java-be
  BACKEND_ECR_REPOSITORY: scan-manager-java
  BACKEND_CONTAINER_NAME: scan-manager-java

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: deploy
          role-to-assume: ${{ env.AWS_ROLE_ARN }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2.0.1

      - name: Build, tag, and push backend image to Amazon ECR
        id: build-backend-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$BACKEND_ECR_REPOSITORY:$IMAGE_TAG ./cloud/services/scan_manager
          docker push $ECR_REGISTRY/$BACKEND_ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$BACKEND_ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Get the current task definition
        id: get-task-def
        run: |
          aws ecs describe-task-definition \
            --task-definition levee-java-be \
            --query taskDefinition \
            --region $AWS_REGION \
            > ./task-def.json

      - name: Render Amazon ECS task definition for backend
        id: render-backend-container
        uses: aws-actions/amazon-ecs-render-task-definition@v1.2.0
        with:
          task-definition: ${{ steps.render-frontend-container.outputs.task-definition }}
          container-name: ${{ env.BACKEND_CONTAINER_NAME }}
          image: ${{ steps.build-backend-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1.4.11
        with:
          task-definition: ${{ steps.render-backend-container.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true

      - name: Post Describe Amazon ECS task definition
        id: post-describe-task-def
        run: |
          rm -f task-def.json